jobs:
  test:
    name: Action
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./run/main

name: Check

on:
  schedule:
    - cron: "45 */6 * * *"
